Multi echo compatibility
TeamXenonDuke/xenon-gas-exchange-consortium pull request #67
Opened 2024-08-09 18:45 UTC by sl609

Add Multi echo compatibility

2024-08-09 22:17 UTC, sl609 commented
Fix the merge conflict but still need to test the code

2024-08-21 16:03 UTC, annacostelle requested changes
Can we add a place in the subject-specific config file (demo config) where we set the multi_echo option to true or false, rather than the base config. That way you don't have to edit both the base and demo configs for a given subject.

2024-09-09 20:48 UTC, Sarahhongqin commented
> That way you don't have to edit

Sup has added line 29: self.multi_echo = False/True to set the multi_echo option.

2024-09-10 16:45 UTC, annacostelle approved these changes

2024-09-10 17:03 UTC, merged